// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnsOhQe7wLcKFfyOBhtGTd2FaKOQwDYA0',
    appId: '1:495395136918:web:52e3d926d4ba46f9cb69b7',
    messagingSenderId: '495395136918',
    projectId: 'todo-app-dec03',
    authDomain: 'todo-app-dec03.firebaseapp.com',
    storageBucket: 'todo-app-dec03.appspot.com',
    measurementId: 'G-51M9RZ5E4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqzZGvKEidqZMz0kvjVeBrilOmmW8zLQ8',
    appId: '1:495395136918:android:a568ed046cb62eb8cb69b7',
    messagingSenderId: '495395136918',
    projectId: 'todo-app-dec03',
    storageBucket: 'todo-app-dec03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jWy-aiAZSswyM-r34xKIwQJzJ9uApPg',
    appId: '1:495395136918:ios:b30ff44497d0c9c8cb69b7',
    messagingSenderId: '495395136918',
    projectId: 'todo-app-dec03',
    storageBucket: 'todo-app-dec03.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jWy-aiAZSswyM-r34xKIwQJzJ9uApPg',
    appId: '1:495395136918:ios:94445d673f66bf4bcb69b7',
    messagingSenderId: '495395136918',
    projectId: 'todo-app-dec03',
    storageBucket: 'todo-app-dec03.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
